=== ganganth/SSC_studentManagemnt_Syatem/XML/dtd/main.dtd
<!ELEMENT main (database, client, usertypes)>
<!ELEMENT database (name, user, password, host)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT user (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT host (#PCDATA)>
<!ELEMENT client (organization)>
<!ELEMENT organization (#PCDATA)>
<!ELEMENT usertypes (usertype+)>
<!ELEMENT usertype EMPTY>
<!ATTLIST usertype module-name CDATA #REQUIRED>
<!ATTLIST usertype basic-properties CDATA #REQUIRED>
<!ATTLIST usertype non-basic-properties CDATA #REQUIRED>
<!ATTLIST usertype to-string-java CDATA #REQUIRED>
<!ATTLIST usertype to-string-ts CDATA #REQUIRED>

=== ganganth/SSC_studentManagemnt_Syatem/XML/main.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE main SYSTEM "./dtd/main.dtd">
<main>
    <database>
        <name>polymathdb</name>
        <user>root</user>
        <password>1234</password>
        <host>localhost:3306</host>
    </database>
    <client>
        <organization>Polymath College</organization>
    </client>
    <usertypes>
        <usertype
                module-name="employee"
                basic-properties="id,code,nametitle,callingname,photo"
                non-basic-properties="civilstatus,fullname,dobirth,gender,nic,mobile,land,email,address,designation,dorecruit,employeestatus,description"
                to-string-java="employee.getCode() + #quat;-#quat; + employee.getNametitle().getName() + #quat; #quat; + employee.getCallingname()"
                to-string-ts="employee.code + '-' + employee.nametitle.name + ' ' + employee.callingname"
        />
        <usertype
                module-name="guardian"
                basic-properties="id,code,nametitle,callingname"
                non-basic-properties=""
                to-string-java="guardian.getCode() + #quat; - #quat; + guardian.getNametitle().getName() + #quat; #quat; + guardian.getCallingname()"
                to-string-ts="guardian.code + ' - ' + guardian.nametitle.name + ' ' + guardian.callingname"
        />
        <usertype
                module-name="student"
                basic-properties="id,indx,callingname"
                non-basic-properties=""
                to-string-java="student.getIndx() + #quat; - #quat; + student.getCallingname()"
                to-string-ts="student.Indx + ' - ' + student.callingname"
        />
    </usertypes>
</main>
