=== ganganth/SSC_studentManagemnt_Syatem/XML/dtd/regular-module.dtd
<!ELEMENT regular-module (code?,(char-property|varchar-property|text-property|int-property|decimal-property|file-property|boolean-property|reference-property|date-property|datetime-property|time-property|multiple-file-property|multiple-reference-property|sub-module|group)+)>
<!ELEMENT sub-module (char-property|varchar-property|text-property|int-property|decimal-property|file-property|boolean-property|reference-property|date-property|datetime-property|time-property)+>
<!ELEMENT group (char-property|varchar-property|text-property|int-property|decimal-property|boolean-property|reference-property|date-property|datetime-property|time-property)+>
<!ELEMENT char-property EMPTY>
<!ELEMENT varchar-property EMPTY>
<!ELEMENT text-property EMPTY>
<!ELEMENT int-property EMPTY>
<!ELEMENT decimal-property EMPTY>
<!ELEMENT file-property EMPTY>
<!ELEMENT multiple-file-property EMPTY>
<!ELEMENT boolean-property EMPTY>
<!ELEMENT reference-property EMPTY>
<!ELEMENT multiple-reference-property EMPTY>
<!ELEMENT date-property EMPTY>
<!ELEMENT datetime-property EMPTY>
<!ELEMENT time-property EMPTY>
<!ELEMENT code EMPTY>

<!ENTITY % width 'width (1|2|3|4|5|6|7|8|9|10|11|12) "12"'>
<!ATTLIST char-property %width;>
<!ATTLIST varchar-property %width;>
<!ATTLIST text-property %width;>
<!ATTLIST int-property %width;>
<!ATTLIST decimal-property %width;>
<!ATTLIST boolean-property %width;>
<!ATTLIST reference-property %width;>
<!ATTLIST date-property %width;>
<!ATTLIST time-property %width;>
<!ATTLIST datetime-property %width;>

<!ATTLIST regular-module name CDATA #REQUIRED>
<!ATTLIST regular-module label CDATA "">
<!ATTLIST regular-module to-string-java CDATA #REQUIRED>
<!ATTLIST regular-module to-string-ts CDATA #REQUIRED>

<!ATTLIST sub-module name CDATA #REQUIRED>
<!ATTLIST sub-module label CDATA #REQUIRED>
<!ATTLIST sub-module min CDATA "0">
<!ATTLIST sub-module max CDATA "0">
<!ATTLIST sub-module insertable (yes|no) "yes">
<!ATTLIST sub-module updatable (yes|no) "yes">
<!ATTLIST sub-module to-string-ts CDATA #REQUIRED>
<!ATTLIST sub-module to-string-java CDATA #REQUIRED>

<!ATTLIST char-property name CDATA #REQUIRED>
<!ATTLIST char-property label CDATA #REQUIRED>
<!ATTLIST char-property example CDATA #REQUIRED>
<!ATTLIST char-property size CDATA #REQUIRED>
<!ATTLIST char-property required (yes|no) "no">
<!ATTLIST char-property unique (yes|no) "no">
<!ATTLIST char-property pattern CDATA "">
<!ATTLIST char-property insertable (yes|no) "yes">
<!ATTLIST char-property updatable (yes|no) "yes">
<!ATTLIST char-property searchable (yes|no) "no">
<!ATTLIST char-property exist-on-table (yes|no) "no">
<!ATTLIST char-property basic (yes|no) "no">
<!ATTLIST char-property default-value CDATA "">


<!ATTLIST varchar-property name CDATA #REQUIRED>
<!ATTLIST varchar-property label CDATA #REQUIRED>
<!ATTLIST varchar-property example CDATA #REQUIRED>
<!ATTLIST varchar-property min-length CDATA "0">
<!ATTLIST varchar-property max-length CDATA "255">
<!ATTLIST varchar-property required (yes|no) "no">
<!ATTLIST varchar-property unique (yes|no) "no">
<!ATTLIST varchar-property pattern CDATA "">
<!ATTLIST varchar-property insertable (yes|no) "yes">
<!ATTLIST varchar-property updatable (yes|no) "yes">
<!ATTLIST varchar-property searchable (yes|no) "no">
<!ATTLIST varchar-property exist-on-table (yes|no) "no">
<!ATTLIST varchar-property basic (yes|no) "no">
<!ATTLIST varchar-property default-value CDATA "">

<!ATTLIST text-property name CDATA #REQUIRED>
<!ATTLIST text-property label CDATA #REQUIRED>
<!ATTLIST text-property example CDATA #REQUIRED>
<!ATTLIST text-property min-length CDATA "0">
<!ATTLIST text-property max-length CDATA "65535">
<!ATTLIST text-property required (yes|no) "no">
<!ATTLIST text-property pattern CDATA "">
<!ATTLIST text-property insertable (yes|no) "yes">
<!ATTLIST text-property updatable (yes|no) "yes">
<!ATTLIST text-property searchable (yes|no) "no">
<!ATTLIST text-property exist-on-table (yes|no) "no">
<!ATTLIST text-property basic (yes|no) "no">
<!ATTLIST text-property default-value CDATA "">

<!ATTLIST int-property name CDATA #REQUIRED>
<!ATTLIST int-property label CDATA #REQUIRED>
<!ATTLIST int-property example CDATA #REQUIRED>
<!ATTLIST int-property size (1|2|3|4|5|6|7|8|9|10|11) "11">
<!ATTLIST int-property min CDATA "-2147483648">
<!ATTLIST int-property max CDATA "2147483647">
<!ATTLIST int-property required (yes|no) "no">
<!ATTLIST int-property unique (yes|no) "no">
<!ATTLIST int-property insertable (yes|no) "yes">
<!ATTLIST int-property updatable (yes|no) "yes">
<!ATTLIST int-property searchable (yes|no) "no">
<!ATTLIST int-property exist-on-table (yes|no) "no">
<!ATTLIST int-property basic (yes|no) "no">
<!ATTLIST int-property default-value CDATA "">

<!ATTLIST decimal-property name CDATA #REQUIRED>
<!ATTLIST decimal-property label CDATA #REQUIRED>
<!ATTLIST decimal-property example CDATA #REQUIRED>
<!ATTLIST decimal-property precision (2|3|5|6|7|8|9|10|11|12|13|14) #REQUIRED>
<!ATTLIST decimal-property scale (1|2|3|4|5) #REQUIRED>
<!ATTLIST decimal-property min CDATA #REQUIRED>
<!ATTLIST decimal-property max CDATA #REQUIRED>
<!ATTLIST decimal-property required (yes|no) "no">
<!ATTLIST decimal-property unique (yes|no) "no">
<!ATTLIST decimal-property insertable (yes|no) "yes">
<!ATTLIST decimal-property updatable (yes|no) "yes">
<!ATTLIST decimal-property searchable (yes|no) "no">
<!ATTLIST decimal-property exist-on-table (yes|no) "no">
<!ATTLIST decimal-property basic (yes|no) "no">
<!ATTLIST decimal-property default-value CDATA "">

<!ATTLIST file-property name CDATA #REQUIRED>
<!ATTLIST file-property label CDATA #REQUIRED>
<!ATTLIST file-property max-file-size CDATA "">
<!ATTLIST file-property accept CDATA "">
<!ATTLIST file-property required (yes|no) "no">
<!ATTLIST file-property insertable (yes|no) "yes">
<!ATTLIST file-property updatable (yes|no) "yes">
<!ATTLIST file-property exist-on-table (yes|no) "no">
<!ATTLIST file-property basic (yes|no) "no">

<!ATTLIST multiple-file-property name CDATA #REQUIRED>
<!ATTLIST multiple-file-property label CDATA #REQUIRED>
<!ATTLIST multiple-file-property max-file-size CDATA "">
<!ATTLIST multiple-file-property accept CDATA "">
<!ATTLIST multiple-file-property insertable (yes|no) "yes">
<!ATTLIST multiple-file-property updatable (yes|no) "yes">
<!ATTLIST multiple-file-property min-count CDATA "0">
<!ATTLIST multiple-file-property max-count CDATA "0">

<!ATTLIST boolean-property name CDATA #REQUIRED>
<!ATTLIST boolean-property label CDATA #REQUIRED>
<!ATTLIST boolean-property yes-text CDATA "Yes">
<!ATTLIST boolean-property insertable (yes|no) "yes">
<!ATTLIST boolean-property updatable (yes|no) "yes">
<!ATTLIST boolean-property searchable (yes|no) "no">
<!ATTLIST boolean-property exist-on-table (yes|no) "no">
<!ATTLIST boolean-property basic (yes|no) "no">
<!ATTLIST boolean-property default-value (true|false) "false">

<!ATTLIST reference-property name CDATA #REQUIRED>
<!ATTLIST reference-property label CDATA #REQUIRED>
<!ATTLIST reference-property required (yes|no) "no">
<!ATTLIST reference-property unique (yes|no) "no">
<!ATTLIST reference-property insertable (yes|no) "yes">
<!ATTLIST reference-property updatable (yes|no) "yes">
<!ATTLIST reference-property searchable (yes|no) "no">
<!ATTLIST reference-property exist-on-table (yes|no) "no">
<!ATTLIST reference-property basic (yes|no) "no">
<!ATTLIST reference-property default-value CDATA "">
<!ATTLIST reference-property to-string-java CDATA #REQUIRED>
<!ATTLIST reference-property to-string-ts CDATA #REQUIRED>
<!ATTLIST reference-property live (yes|no) "yes">
<!ATTLIST reference-property service-method (getAll|getAllBasic) #REQUIRED>
<!ATTLIST reference-property referenced-from CDATA #REQUIRED>
<!--
<!ATTLIST reference-property form-controller (mat-select|search-select|switches|radio) "mat-select">
-->

<!ATTLIST multiple-reference-property name CDATA #REQUIRED>
<!ATTLIST multiple-reference-property label CDATA #REQUIRED>
<!ATTLIST multiple-reference-property min-count CDATA "0">
<!ATTLIST multiple-reference-property max-count CDATA "0">
<!ATTLIST multiple-reference-property insertable (yes|no) "yes">
<!ATTLIST multiple-reference-property updatable (yes|no) "yes">
<!ATTLIST multiple-reference-property to-string-java CDATA #REQUIRED>
<!ATTLIST multiple-reference-property to-string-ts CDATA #REQUIRED>
<!ATTLIST multiple-reference-property service-method (getAll|getAllBasic) #REQUIRED>
<!ATTLIST multiple-reference-property referenced-from CDATA #REQUIRED>
<!--
<!ATTLIST multiple-reference-property form-controller (dual-listbox|mat-select|search-select|checkbox) "dual-listbox">
-->

<!ATTLIST date-property name CDATA #REQUIRED>
<!ATTLIST date-property label CDATA #REQUIRED>
<!ATTLIST date-property example CDATA #REQUIRED><!--
<!ATTLIST date-property min CDATA "">
<!ATTLIST date-property max CDATA "">-->
<!ATTLIST date-property required (yes|no) "no">
<!ATTLIST date-property unique (yes|no) "no">
<!ATTLIST date-property insertable (yes|no) "yes">
<!ATTLIST date-property updatable (yes|no) "yes"><!--
<!ATTLIST date-property searchable (yes|no) "no">-->
<!ATTLIST date-property exist-on-table (yes|no) "no">
<!ATTLIST date-property basic (yes|no) "no">
<!ATTLIST date-property default-value CDATA "">

<!ATTLIST datetime-property name CDATA #REQUIRED>
<!ATTLIST datetime-property label CDATA #REQUIRED>
<!ATTLIST datetime-property example CDATA #REQUIRED>
<!--<!ATTLIST datetime-property min CDATA "">
<!ATTLIST datetime-property max CDATA "">-->
<!ATTLIST datetime-property required (yes|no) "no">
<!ATTLIST datetime-property unique (yes|no) "no">
<!ATTLIST datetime-property insertable (yes|no) "yes">
<!ATTLIST datetime-property updatable (yes|no) "yes"><!--
<!ATTLIST datetime-property searchable (yes|no) "no">-->
<!ATTLIST datetime-property exist-on-table (yes|no) "no">
<!ATTLIST datetime-property basic (yes|no) "no">
<!ATTLIST datetime-property default-value CDATA "">

<!ATTLIST time-property name CDATA #REQUIRED>
<!ATTLIST time-property label CDATA #REQUIRED>
<!ATTLIST time-property example CDATA #REQUIRED>
<!--<!ATTLIST time-property min CDATA "">
<!ATTLIST time-property max CDATA "">-->
<!ATTLIST time-property required (yes|no) "no">
<!ATTLIST time-property unique (yes|no) "no">
<!ATTLIST time-property insertable (yes|no) "yes">
<!ATTLIST time-property updatable (yes|no) "yes">
<!--<!ATTLIST time-property searchable (yes|no) "no">-->
<!ATTLIST time-property exist-on-table (yes|no) "no">
<!ATTLIST time-property basic (yes|no) "no">
<!ATTLIST time-property default-value CDATA "">

<!ATTLIST code length CDATA #REQUIRED>
<!ATTLIST code prefix CDATA "">
<!ATTLIST code yearly-renew (yes|no) "yes">
<!ATTLIST code insertable (yes|no) "no">
<!ATTLIST code searchable (yes|no) "no">
<!ATTLIST code exist-on-table (yes|no) "no">

=== ganganth/SSC_studentManagemnt_Syatem/XML/modules/gradeyear.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE regular-module SYSTEM "../dtd/regular-module.dtd">
<regular-module name="gradeyear" to-string-ts="gradeyear.code + '-' + gradeyear.year" to-string-java="gradeyear.getCode() + #quat; #quat; + gradeyear.getYear()">
    <code length="10" prefix="GY" searchable="yes" exist-on-table="yes"/>

    <varchar-property name="year" label="Year" example="" required="yes" exist-on-table="yes"/>

    <date-property name="dostart" label="Start Date" example="" required="yes" exist-on-table="yes"/>
    <date-property name="doend" label="End Date" example="" required="yes" exist-on-table="yes"/>

    <decimal-property name="totalfee" label="Total Fee" example="" precision="10" scale="2" min="0" max="99999999"/>


    <reference-property basic="yes" required="yes" name="grade" label="Grade" referenced-from="grade" service-method="getAll" to-string-java="grade.getName()" to-string-ts="grade.name"/>
    <reference-property basic="yes" required="yes" name="gradeyearstatus" label="Grade Year Status" referenced-from="gradeyearstatus" service-method="getAll" to-string-java="gradeyearstatus.getName()" to-string-ts="gradeyearstatus.name"/>

    <sub-module name="yearterm" label="Yar Term Payments" to-string-ts="yearterm.id" to-string-java="yearterm.getId()">
        <reference-property name="payscheme" label="Pay Scheme" to-string-java="payscheme.getName()" to-string-ts="payscheme.name" service-method="getAll"
                            referenced-from="payscheme"/>
        <date-property name="date" label="Date" example="" required="yes"/>
        <decimal-property name="fee" label="Fee" example="" precision="10" scale="2" min="0" max="999999999"/>
    </sub-module>

    <text-property name="description" label="Description" example=""/>


</regular-module>

=== ganganth/SSC_studentManagemnt_Syatem/XML/modules/subject.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE regular-module SYSTEM "../dtd/regular-module.dtd">
<regular-module name="subject" to-string-ts="subject.code" to-string-java="subject.getCode()">
    <code length="10" prefix="S" searchable="yes" exist-on-table="yes"/>

    <varchar-property name="name" label="Subject Name" example="" required="yes" exist-on-table="yes" searchable="yes"/>

    <reference-property searchable="yes" required="yes" name="grade" label="Grade" referenced-from="grade" service-method="getAll" to-string-java="grade.getName()" to-string-ts="grade.name"/>
    <reference-property searchable="yes" required="yes" name="medium" label="Medium" referenced-from="medium" service-method="getAll" to-string-java="medium.getName()" to-string-ts="medium.name"/>

    <multiple-reference-property name="subjectteacher" label="Subject Teacher" to-string-java="employee.getCode() + #quat;-#quat; + employee.getNametitle.getName() + #quat; #quat; + employee.getCallingname()" to-string-ts="employee.code + '-' + employee.nametitle.name + ' ' + employee.callingname" service-method="getAllBasic"
                                 referenced-from="employee"/>


    <reference-property required="yes" name="subjectstatus" label="Subject Status" referenced-from="subjectstatus" service-method="getAll" to-string-java="subjectstatus.getName()" to-string-ts="subjectstatus.name"/>


    <text-property name="description" label="Description" example=""/>


</regular-module>

=== ganganth/SSC_studentManagemnt_Syatem/XML/modules/guardian.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE regular-module SYSTEM "../dtd/regular-module.dtd">
<regular-module name="guardian" to-string-ts="guardian.code + '-' + guardian.nametitle.name + ' ' + guardian.callingname" to-string-java="guardian.getCode() + #quat;-#quat; + guardian.getNametitle.getName() + #quat; #quat; + guardian.getCallingname()">
    <code length="10" prefix="GU" searchable="yes" exist-on-table="yes"/>
    <group>
        <reference-property basic="yes" required="yes" width="4" name="nametitle" label="Title" referenced-from="nametitle" service-method="getAll" to-string-java="nametitle.getName()" to-string-ts="nametitle.name"/>
        <varchar-property basic="yes" exist-on-table="yes" searchable="yes" required="yes" width="8" name="callingname" label="Calling Name" example="Sandun"/>
    </group>
    <group>
        <reference-property width="4" name="civilstatus" label="Civilstatus" referenced-from="civilstatus" service-method="getAll" to-string-ts="civilstatus.name" to-string-java="civilstatus.getName()"/>
        <varchar-property width="8" required="yes" name="fullname" label="Full Name" example="Kamal Perera"/>
    </group>

    <reference-property name="gender" label="Gender" referenced-from="gender" service-method="getAll" to-string-java="gender.getName()" to-string-ts="gender.name"/>
    <varchar-property unique="yes" required="yes" exist-on-table="yes" searchable="yes"  name="nic" label="NIC Number" example="940081009V" min-length="10" max-length="12" pattern="^(([0-9]{12})|([0-9]{9}[vVxX]))$"/>


    <group>
        <char-property unique="yes" name="mobile" label="Mobile Number" example="0789456123" size="10" required="yes" width="4" pattern="^([0][0-9]{9})$"/>
        <char-property name="land" label="Land Number" example="0789455123" size="10" width="4" pattern="^([0][0-9]{9})$"/>
        <varchar-property unique="yes" width="4" name="email" label="Email Address" example="user@gmail.com" min-length="5" pattern="^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$"/>
    </group>

    <varchar-property width="6" name="occupation" label="Occupation" example="Doctor" min-length="4" />

    <text-property name="address" label="Home Address" example="123, Colombo Road, Gampaha" min-length="4" required="yes"/>


    <char-property name="officetel1" label="Office Number 1" example="0789456123" size="10" pattern="^([0][0-9]{9})$"/>
    <char-property name="officetel2" label="Office Number 2" example="0339455123" size="10" pattern="^([0][0-9]{9})$"/>

    <text-property name="officeaddress" label="Office Address" example="123, Colombo Road, Gampaha" min-length="4" required="yes"/>


    <text-property name="description" label="Description" example=""/>

</regular-module>

=== ganganth/SSC_studentManagemnt_Syatem/XML/modules/exam.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE regular-module SYSTEM "../dtd/regular-module.dtd">
<regular-module name="exam" to-string-ts="exam.code" to-string-java="exam.getCode()">
    <code length="10" prefix="EX" searchable="yes" exist-on-table="yes"/>


    <date-property required="yes" exist-on-table="yes" name="date" label="Exam Date" example=""/>

    <time-property name="tostart" label="Start Time" example="" required="yes" exist-on-table="yes"/>

    <time-property name="toend" label="End Time" example="" required="yes" exist-on-table="yes"/>

    <reference-property required="yes" name="gradeyear" label="Grade Year" referenced-from="gradeyear" service-method="getAllBasic" to-string-java="gradeyear.getCode() + #quat; #quat; + gradeyear.getYear()" to-string-ts="gradeyear.code + '-' + gradeyear.year"/>

    <reference-property required="yes" name="subject" exist-on-table="yes" label="Subject" referenced-from="subject" service-method="getAllBasic" to-string-java="subject.getCode() + #quat; #quat; + subject.getName()" to-string-ts="subject.code + '-' + subject.name"/>

    <reference-property exist-on-table="yes" insertable="no" default-value="1" required="yes" name="examstatus" label="Exam Status" referenced-from="examstatus" service-method="getAll" to-string-java="examstatus.getName()" to-string-ts="examstatus.name"/>
    
    <text-property name="description" label="Description" example=""/>


</regular-module>

=== ganganth/SSC_studentManagemnt_Syatem/XML/modules/material.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE regular-module SYSTEM "../dtd/regular-module.dtd">
<regular-module name="material" to-string-ts="material.code + '-' + material.title" to-string-java="material.getCode() + #quat;-#quat; + material.getTitle()">

    <code length="10" prefix="MAT" searchable="yes" exist-on-table="yes"/>
    
    <varchar-property name="name" label="Material Title" example="Grade 8 Mathematics Trigonometry" basic="yes" searchable="yes" exist-on-table="yes" required="yes"/>

    <file-property name="file" label="Digital Copy" accept="application/pdf"/>

    <reference-property searchable="yes" required="yes" exist-on-table="yes" name="subject" label="Subject" referenced-from="subject" service-method="getAllBasic" to-string-java="subject.getCode() + #quat; #quat; + subject.getName()" to-string-ts="subject.code + '-' + subject.name"/>
    <reference-property searchable="yes" required="yes" exist-on-table="yes" name="lesson" label="Lesson" referenced-from="lesson" service-method="getAllBasic" to-string-java="lesson.getName()" to-string-ts="lesson.name"/>

    <date-property name="date" label="Publishing Date" example="02-03-2022"/>

    <reference-property name="employee" label="Teacher" to-string-java="employee.getNametitle().getName() + #quat;-#quat; + employee.getCallingname()" to-string-ts="employee.nametitle.name + '-' + employee.callingname" service-method="getAllBasic" referenced-from="employee"/>

    <reference-property required="yes" searchable="yes" exist-on-table="yes" name="materialmedium" label="Material Medium" referenced-from="materialmedium" service-method="getAll" to-string-java="materialmedium.getName()" to-string-ts="materialmedium.name"/>

    <reference-property  width="4" required="yes" default-value="1" insertable="no" searchable="yes" exist-on-table="yes" name="materialstatus" label="Material Status" referenced-from="materialstatus" service-method="getAll" to-string-java="materialstatus.getName()" to-string-ts="materialstatus.name"/>

    <text-property name="description" label="Description" example=""/>

</regular-module>

=== ganganth/SSC_studentManagemnt_Syatem/XML/modules/examresult.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE regular-module SYSTEM "../dtd/regular-module.dtd">
<regular-module name="examresult" to-string-ts="examresult.code" to-string-java="examresult.getCode()">

    <code length="10" prefix="ER" searchable="yes" exist-on-table="yes"/>

    <reference-property exist-on-table="yes" name="exam" label="Exam" to-string-java="exam.getName()" to-string-ts="exam.name" service-method="getAllBasic" referenced-from="exam" basic="yes"/>

    <reference-property basic="yes" required="yes" name="student" label="Student" referenced-from="student" service-method="getAllBasic" to-string-java="student.getCode() + #quat;-#quat; + student.getNametitle.getName() + #quat; #quat; + student.getCallingname()" to-string-ts="student.code + '-' + student.nametitle.name + ' ' + student.callingname"/>

    <boolean-property name="isprersent" label="Is Present" exist-on-table="yes" searchable="yes" yes-text="is Present"/>

    <group>
        <decimal-property width="6" name="marks" label="Marks" example="78" precision="5" scale="2" min="0" max="100" />

        <varchar-property width="6" name="grade" label="Grade" example="A+"/>
    </group>

    <text-property name="feedback" label="Teacher Feedback" example=""/>

    <text-property name="description" label="Description" example=""/>
</regular-module>

=== ganganth/SSC_studentManagemnt_Syatem/XML/modules/clssession.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE regular-module SYSTEM "../dtd/regular-module.dtd">
<regular-module name="clssession" to-string-ts="clssession.code" to-string-java="clssession.getCode()">
    <code length="10" prefix="CS" searchable="yes" exist-on-table="yes"/>

    <reference-property required="yes" exist-on-table="yes" searchable="yes" name="cls" label="Class" to-string-java="cls.getName()" to-string-ts="class.name" service-method="getAllBasic" referenced-from="cls"/>

    <reference-property searchable="yes" exist-on-table="yes" required="yes" name="grade" label="Grade" referenced-from="grade" service-method="getAll" to-string-java="grade.getName()" to-string-ts="grade.name"/>

    <reference-property required="yes"  name="timetable" label="Time Table" to-string-java="timetable.getCode()" to-string-ts="timetable.code" service-method="getAllBasic" referenced-from="timetable"/>

    <reference-property required="yes" name="clssessionstatus" label="Clssession Status" referenced-from="clssessionstatus" service-method="getAll" to-string-java="clssessionstatus.getName()" to-string-ts="clssessionstatus.name"/>

    <reference-property required="yes" exist-on-table="yes" name="sheduledate" label="Schedule Date" to-string-java="sheduledate.getCode() + #quat;-#quat; + sheduledate.getDate()" to-string-ts="sheduledate.code + '-' sheduledate.date" service-method="getAllBasic" referenced-from="sheduledate"/>

    <text-property name="description" label="Description" example=""/>

    <multiple-reference-property name="clssessionlesson" label="Class Lesson" to-string-java="lesson.getName()" to-string-ts="lesson.name" service-method="getAllBasic" referenced-from="lesson"/>

</regular-module>

=== ganganth/SSC_studentManagemnt_Syatem/XML/modules/student.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE regular-module SYSTEM "../dtd/regular-module.dtd">
<regular-module name="student" to-string-ts="student.code + '-' + student.nametitle.name + ' ' + student.callingname" to-string-java="student.getCode() + #quat;-#quat; + student.getNametitle.getName() + #quat; #quat; + student.getCallingname()">
    <code length="10" prefix="ST" searchable="yes" exist-on-table="yes"/>

    <group>
        <reference-property basic="yes" required="yes" width="4" name="nametitle" label="Title" referenced-from="nametitle" service-method="getAll" to-string-java="nametitle.getName()" to-string-ts="nametitle.name"/>
        <varchar-property basic="yes" exist-on-table="yes" searchable="yes" required="yes" width="8" name="callingname" label="Calling Name" example="Sandun"/>
    </group>
    <group>
        <varchar-property  required="yes" name="fullname" label="Full Name" example="Kamal Perera"/>
    </group>
    <file-property basic="yes" name="photo" label="Photo" accept="image/*" exist-on-table="yes"/>
    <file-property basic="yes" name="birthcertificate" label="Birth Certificate" accept="image/*" exist-on-table="yes"/>
    <group>
        <date-property required="yes" width="4" name="dobirth" label="Date Of Birth" example="1994-12-31"/>
        <reference-property required="yes" width="4" name="gender" label="Gender" referenced-from="gender" service-method="getAll" to-string-java="gender.getName()" to-string-ts="gender.name"/>
        <varchar-property unique="yes" exist-on-table="yes" searchable="yes" width="4" name="nic" label="NIC Number" example="940081009V" min-length="10" max-length="12" pattern="^(([0-9]{12})|([0-9]{9}[vVxX]))$"/>
    </group>


    <reference-property  name="guardian" label="Guardian" referenced-from="guardian" service-method="getAllBasic" to-string-java="guardian.getCallingName()+ #quat; #quat; + guardian.getNic()" to-string-ts="guardian.callingname + ' ' + guardian.nic"/>
    <reference-property  name="guardianrelationship" label="Guardian Relationship" referenced-from="guardianrelationship" service-method="getAll" to-string-java="guardianrelationship.getName()" to-string-ts="guardianrelationship.name"/>
    <reference-property  name="bloodtype" label="Blood Type" referenced-from="bloodtype" service-method="getAll" to-string-java="bloodtype.getName()" to-string-ts="bloodtype.name"/>
    <reference-property  name="religion" label="Religion" referenced-from="religion" service-method="getAll" to-string-java="religion.getName()" to-string-ts="religion.name"/>
    <reference-property  name="ethnicity" label="Ethnicity" referenced-from="ethnicity" service-method="getAll" to-string-java="ethnicity.getName()" to-string-ts="ethnicity.name"/>
    <reference-property  name="house" label="House" referenced-from="house" service-method="getAll" to-string-java="house.getName()" to-string-ts="house.name"/>
    <reference-property exist-on-table="yes" insertable="no" default-value="1"  name="studentstatus" label="Student Status" referenced-from="studentstatus" service-method="getAll" to-string-java="studentstatus.getName()" to-string-ts="studentstatus.name"/>


    <group>
        <char-property unique="yes" name="mobile" label="Mobile Number" example="0789456123" size="10" required="yes" width="4" pattern="^([0][0-9]{9})$"/>
        <char-property name="land" label="Land Number" example="0789455123" size="10" width="4" pattern="^([0][0-9]{9})$"/>
        <varchar-property unique="yes" width="4" name="email" label="Email Address" example="user@gmail.com" min-length="5" pattern="^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$"/>
    </group>



    
    <date-property name="joineddate" label="Joined Date" example="" exist-on-table="yes" required="yes"/>



    <text-property name="address" label="Address" example="123, Colombo Road, Gampaha" min-length="4" required="yes"/>


    <decimal-property name="admissionfee" label="Admission Fee" example="" precision="10" scale="2" min="0" max="99999999"/>



    <text-property name="description" label="Description" example=""/>


</regular-module>
