=== ganganth/SSC_studentManagemnt_Syatem/XML/dtd/regular-module.dtd
<!ELEMENT regular-module (code?,(char-property|varchar-property|text-property|int-property|decimal-property|file-property|boolean-property|reference-property|date-property|datetime-property|time-property|multiple-file-property|multiple-reference-property|sub-module|group)+)>
<!ELEMENT sub-module (char-property|varchar-property|text-property|int-property|decimal-property|file-property|boolean-property|reference-property|date-property|datetime-property|time-property)+>
<!ELEMENT group (char-property|varchar-property|text-property|int-property|decimal-property|boolean-property|reference-property|date-property|datetime-property|time-property)+>
<!ELEMENT char-property EMPTY>
<!ELEMENT varchar-property EMPTY>
<!ELEMENT text-property EMPTY>
<!ELEMENT int-property EMPTY>
<!ELEMENT decimal-property EMPTY>
<!ELEMENT file-property EMPTY>
<!ELEMENT multiple-file-property EMPTY>
<!ELEMENT boolean-property EMPTY>
<!ELEMENT reference-property EMPTY>
<!ELEMENT multiple-reference-property EMPTY>
<!ELEMENT date-property EMPTY>
<!ELEMENT datetime-property EMPTY>
<!ELEMENT time-property EMPTY>
<!ELEMENT code EMPTY>

<!ENTITY % width 'width (1|2|3|4|5|6|7|8|9|10|11|12) "12"'>
<!ATTLIST char-property %width;>
<!ATTLIST varchar-property %width;>
<!ATTLIST text-property %width;>
<!ATTLIST int-property %width;>
<!ATTLIST decimal-property %width;>
<!ATTLIST boolean-property %width;>
<!ATTLIST reference-property %width;>
<!ATTLIST date-property %width;>
<!ATTLIST time-property %width;>
<!ATTLIST datetime-property %width;>

<!ATTLIST regular-module name CDATA #REQUIRED>
<!ATTLIST regular-module label CDATA "">
<!ATTLIST regular-module to-string-java CDATA #REQUIRED>
<!ATTLIST regular-module to-string-ts CDATA #REQUIRED>

<!ATTLIST sub-module name CDATA #REQUIRED>
<!ATTLIST sub-module label CDATA #REQUIRED>
<!ATTLIST sub-module min CDATA "0">
<!ATTLIST sub-module max CDATA "0">
<!ATTLIST sub-module insertable (yes|no) "yes">
<!ATTLIST sub-module updatable (yes|no) "yes">
<!ATTLIST sub-module to-string-ts CDATA #REQUIRED>
<!ATTLIST sub-module to-string-java CDATA #REQUIRED>

<!ATTLIST char-property name CDATA #REQUIRED>
<!ATTLIST char-property label CDATA #REQUIRED>
<!ATTLIST char-property example CDATA #REQUIRED>
<!ATTLIST char-property size CDATA #REQUIRED>
<!ATTLIST char-property required (yes|no) "no">
<!ATTLIST char-property unique (yes|no) "no">
<!ATTLIST char-property pattern CDATA "">
<!ATTLIST char-property insertable (yes|no) "yes">
<!ATTLIST char-property updatable (yes|no) "yes">
<!ATTLIST char-property searchable (yes|no) "no">
<!ATTLIST char-property exist-on-table (yes|no) "no">
<!ATTLIST char-property basic (yes|no) "no">
<!ATTLIST char-property default-value CDATA "">


<!ATTLIST varchar-property name CDATA #REQUIRED>
<!ATTLIST varchar-property label CDATA #REQUIRED>
<!ATTLIST varchar-property example CDATA #REQUIRED>
<!ATTLIST varchar-property min-length CDATA "0">
<!ATTLIST varchar-property max-length CDATA "255">
<!ATTLIST varchar-property required (yes|no) "no">
<!ATTLIST varchar-property unique (yes|no) "no">
<!ATTLIST varchar-property pattern CDATA "">
<!ATTLIST varchar-property insertable (yes|no) "yes">
<!ATTLIST varchar-property updatable (yes|no) "yes">
<!ATTLIST varchar-property searchable (yes|no) "no">
<!ATTLIST varchar-property exist-on-table (yes|no) "no">
<!ATTLIST varchar-property basic (yes|no) "no">
<!ATTLIST varchar-property default-value CDATA "">

<!ATTLIST text-property name CDATA #REQUIRED>
<!ATTLIST text-property label CDATA #REQUIRED>
<!ATTLIST text-property example CDATA #REQUIRED>
<!ATTLIST text-property min-length CDATA "0">
<!ATTLIST text-property max-length CDATA "65535">
<!ATTLIST text-property required (yes|no) "no">
<!ATTLIST text-property pattern CDATA "">
<!ATTLIST text-property insertable (yes|no) "yes">
<!ATTLIST text-property updatable (yes|no) "yes">
<!ATTLIST text-property searchable (yes|no) "no">
<!ATTLIST text-property exist-on-table (yes|no) "no">
<!ATTLIST text-property basic (yes|no) "no">
<!ATTLIST text-property default-value CDATA "">

<!ATTLIST int-property name CDATA #REQUIRED>
<!ATTLIST int-property label CDATA #REQUIRED>
<!ATTLIST int-property example CDATA #REQUIRED>
<!ATTLIST int-property size (1|2|3|4|5|6|7|8|9|10|11) "11">
<!ATTLIST int-property min CDATA "-2147483648">
<!ATTLIST int-property max CDATA "2147483647">
<!ATTLIST int-property required (yes|no) "no">
<!ATTLIST int-property unique (yes|no) "no">
<!ATTLIST int-property insertable (yes|no) "yes">
<!ATTLIST int-property updatable (yes|no) "yes">
<!ATTLIST int-property searchable (yes|no) "no">
<!ATTLIST int-property exist-on-table (yes|no) "no">
<!ATTLIST int-property basic (yes|no) "no">
<!ATTLIST int-property default-value CDATA "">

<!ATTLIST decimal-property name CDATA #REQUIRED>
<!ATTLIST decimal-property label CDATA #REQUIRED>
<!ATTLIST decimal-property example CDATA #REQUIRED>
<!ATTLIST decimal-property precision (2|3|5|6|7|8|9|10|11|12|13|14) #REQUIRED>
<!ATTLIST decimal-property scale (1|2|3|4|5) #REQUIRED>
<!ATTLIST decimal-property min CDATA #REQUIRED>
<!ATTLIST decimal-property max CDATA #REQUIRED>
<!ATTLIST decimal-property required (yes|no) "no">
<!ATTLIST decimal-property unique (yes|no) "no">
<!ATTLIST decimal-property insertable (yes|no) "yes">
<!ATTLIST decimal-property updatable (yes|no) "yes">
<!ATTLIST decimal-property searchable (yes|no) "no">
<!ATTLIST decimal-property exist-on-table (yes|no) "no">
<!ATTLIST decimal-property basic (yes|no) "no">
<!ATTLIST decimal-property default-value CDATA "">

<!ATTLIST file-property name CDATA #REQUIRED>
<!ATTLIST file-property label CDATA #REQUIRED>
<!ATTLIST file-property max-file-size CDATA "">
<!ATTLIST file-property accept CDATA "">
<!ATTLIST file-property required (yes|no) "no">
<!ATTLIST file-property insertable (yes|no) "yes">
<!ATTLIST file-property updatable (yes|no) "yes">
<!ATTLIST file-property exist-on-table (yes|no) "no">
<!ATTLIST file-property basic (yes|no) "no">

<!ATTLIST multiple-file-property name CDATA #REQUIRED>
<!ATTLIST multiple-file-property label CDATA #REQUIRED>
<!ATTLIST multiple-file-property max-file-size CDATA "">
<!ATTLIST multiple-file-property accept CDATA "">
<!ATTLIST multiple-file-property insertable (yes|no) "yes">
<!ATTLIST multiple-file-property updatable (yes|no) "yes">
<!ATTLIST multiple-file-property min-count CDATA "0">
<!ATTLIST multiple-file-property max-count CDATA "0">

<!ATTLIST boolean-property name CDATA #REQUIRED>
<!ATTLIST boolean-property label CDATA #REQUIRED>
<!ATTLIST boolean-property yes-text CDATA "Yes">
<!ATTLIST boolean-property insertable (yes|no) "yes">
<!ATTLIST boolean-property updatable (yes|no) "yes">
<!ATTLIST boolean-property searchable (yes|no) "no">
<!ATTLIST boolean-property exist-on-table (yes|no) "no">
<!ATTLIST boolean-property basic (yes|no) "no">
<!ATTLIST boolean-property default-value (true|false) "false">

<!ATTLIST reference-property name CDATA #REQUIRED>
<!ATTLIST reference-property label CDATA #REQUIRED>
<!ATTLIST reference-property required (yes|no) "no">
<!ATTLIST reference-property unique (yes|no) "no">
<!ATTLIST reference-property insertable (yes|no) "yes">
<!ATTLIST reference-property updatable (yes|no) "yes">
<!ATTLIST reference-property searchable (yes|no) "no">
<!ATTLIST reference-property exist-on-table (yes|no) "no">
<!ATTLIST reference-property basic (yes|no) "no">
<!ATTLIST reference-property default-value CDATA "">
<!ATTLIST reference-property to-string-java CDATA #REQUIRED>
<!ATTLIST reference-property to-string-ts CDATA #REQUIRED>
<!ATTLIST reference-property live (yes|no) "yes">
<!ATTLIST reference-property service-method (getAll|getAllBasic) #REQUIRED>
<!ATTLIST reference-property referenced-from CDATA #REQUIRED>
<!--
<!ATTLIST reference-property form-controller (mat-select|search-select|switches|radio) "mat-select">
-->

<!ATTLIST multiple-reference-property name CDATA #REQUIRED>
<!ATTLIST multiple-reference-property label CDATA #REQUIRED>
<!ATTLIST multiple-reference-property min-count CDATA "0">
<!ATTLIST multiple-reference-property max-count CDATA "0">
<!ATTLIST multiple-reference-property insertable (yes|no) "yes">
<!ATTLIST multiple-reference-property updatable (yes|no) "yes">
<!ATTLIST multiple-reference-property to-string-java CDATA #REQUIRED>
<!ATTLIST multiple-reference-property to-string-ts CDATA #REQUIRED>
<!ATTLIST multiple-reference-property service-method (getAll|getAllBasic) #REQUIRED>
<!ATTLIST multiple-reference-property referenced-from CDATA #REQUIRED>
<!--
<!ATTLIST multiple-reference-property form-controller (dual-listbox|mat-select|search-select|checkbox) "dual-listbox">
-->

<!ATTLIST date-property name CDATA #REQUIRED>
<!ATTLIST date-property label CDATA #REQUIRED>
<!ATTLIST date-property example CDATA #REQUIRED><!--
<!ATTLIST date-property min CDATA "">
<!ATTLIST date-property max CDATA "">-->
<!ATTLIST date-property required (yes|no) "no">
<!ATTLIST date-property unique (yes|no) "no">
<!ATTLIST date-property insertable (yes|no) "yes">
<!ATTLIST date-property updatable (yes|no) "yes"><!--
<!ATTLIST date-property searchable (yes|no) "no">-->
<!ATTLIST date-property exist-on-table (yes|no) "no">
<!ATTLIST date-property basic (yes|no) "no">
<!ATTLIST date-property default-value CDATA "">

<!ATTLIST datetime-property name CDATA #REQUIRED>
<!ATTLIST datetime-property label CDATA #REQUIRED>
<!ATTLIST datetime-property example CDATA #REQUIRED>
<!--<!ATTLIST datetime-property min CDATA "">
<!ATTLIST datetime-property max CDATA "">-->
<!ATTLIST datetime-property required (yes|no) "no">
<!ATTLIST datetime-property unique (yes|no) "no">
<!ATTLIST datetime-property insertable (yes|no) "yes">
<!ATTLIST datetime-property updatable (yes|no) "yes"><!--
<!ATTLIST datetime-property searchable (yes|no) "no">-->
<!ATTLIST datetime-property exist-on-table (yes|no) "no">
<!ATTLIST datetime-property basic (yes|no) "no">
<!ATTLIST datetime-property default-value CDATA "">

<!ATTLIST time-property name CDATA #REQUIRED>
<!ATTLIST time-property label CDATA #REQUIRED>
<!ATTLIST time-property example CDATA #REQUIRED>
<!--<!ATTLIST time-property min CDATA "">
<!ATTLIST time-property max CDATA "">-->
<!ATTLIST time-property required (yes|no) "no">
<!ATTLIST time-property unique (yes|no) "no">
<!ATTLIST time-property insertable (yes|no) "yes">
<!ATTLIST time-property updatable (yes|no) "yes">
<!--<!ATTLIST time-property searchable (yes|no) "no">-->
<!ATTLIST time-property exist-on-table (yes|no) "no">
<!ATTLIST time-property basic (yes|no) "no">
<!ATTLIST time-property default-value CDATA "">

<!ATTLIST code length CDATA #REQUIRED>
<!ATTLIST code prefix CDATA "">
<!ATTLIST code yearly-renew (yes|no) "yes">
<!ATTLIST code insertable (yes|no) "no">
<!ATTLIST code searchable (yes|no) "no">
<!ATTLIST code exist-on-table (yes|no) "no">

=== ganganth/SSC_studentManagemnt_Syatem/XML/modules/timetable.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE regular-module SYSTEM "../dtd/regular-module.dtd">
<regular-module name="timetable" to-string-ts="timetable.code" to-string-java="timetable.getCode()">
    <code length="10" prefix="TT" searchable="yes" exist-on-table="yes"/>

    <reference-property searchable="yes" exist-on-table="yes" required="yes" name="grade" label="Grade" referenced-from="grade" service-method="getAll" to-string-java="grade.getName()" to-string-ts="grade.name"/>

    <reference-property searchable="yes" exist-on-table="yes" required="yes" name="gradeyear" label="Grade Year" referenced-from="gradeyear" service-method="getAllBasic" to-string-java="gradeyear.getCode() + #quat; #quat; + gradeyear.getYear()" to-string-ts="gradeyear.code + '-' + gradeyear.year"/>

    <reference-property searchable="yes" required="yes" exist-on-table="yes" name="subject" label="Subject" referenced-from="subject" service-method="getAllBasic" to-string-java="subject.getCode() + #quat; #quat; + subject.getName()" to-string-ts="subject.code + '-' + subject.name"/>

    <reference-property exist-on-table="yes" searchable="yes" required="yes" name="teacher" label="Subject Teacher" to-string-java="teacher.getCode() + #quat;-#quat; + teacher.getNametitle().getName() + #quat; #quat; + teacher.getCallingname()" to-string-ts="teacher.code + '-' + teacher.nametitle.name + ' ' + teacher.callingname" service-method="getAllBasic"
                        referenced-from="employee"/>

    <reference-property required="yes" exist-on-table="yes" name="day" label="Day" referenced-from="day" service-method="getAll" to-string-java="day.getName()" to-string-ts="day.name"/>

    <reference-property required="yes" exist-on-table="yes" searchable="yes" name="cls" label="Class" to-string-java="cls.getName()" to-string-ts="cls.name" service-method="getAllBasic" referenced-from="cls"/>

    <reference-property required="yes" name="timetablestatus" label="Timetable Status" referenced-from="timetablestatus" service-method="getAll" to-string-java="timetablestatus.getName()" to-string-ts="timetablestatus.name"/>

    <text-property name="description" label="Description" example=""/>

    <time-property required="yes" exist-on-table="yes" name="tostart" label="Start Time" example=""/>
    <time-property required="yes" exist-on-table="yes" name="toend" label="End Time" example=""/>


</regular-module>

=== ganganth/SSC_studentManagemnt_Syatem/XML/modules/studentpayment.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE regular-module SYSTEM "../dtd/regular-module.dtd">
<regular-module name="studentpayment" to-string-ts="studentpayment.code" to-string-java="studentpayment.getCode()">
    <code length="10" prefix="P" searchable="yes" exist-on-table="yes"/>

    <reference-property basic="yes" exist-on-table="yes" required="yes" name="student" label="Student" referenced-from="student" service-method="getAllBasic" to-string-java="student.getCode() + #quat;-#quat; + student.getNametitle.getName() + #quat; #quat; + student.getCallingname()" to-string-ts="student.code + '-' + student.nametitle.name + ' ' + student.callingname"/>


    <reference-property basic="yes" exist-on-table="yes" required="yes" name="enrollment" label="Enrollment" referenced-from="enrollment" service-method="getAllBasic" to-string-java="enrollment.getCode()" to-string-ts="enrollment.code"/>




    <decimal-property insertable="no" updatable="no" name="prevbalance" label="Previous Balance" example="" precision="10" scale="2" min="0" max="999999"/>
    <decimal-property required="yes" exist-on-table="yes" name="amount" label="Amount" example="" precision="10" scale="2" min="0" max="999999"/>
    <decimal-property  insertable="no" updatable="no" exist-on-table="yes"  name="balance" label="Balance" example="" precision="10" scale="2" min="0" max="999999"/>

    <int-property insertable="no" updatable="no" exist-on-table="yes" name="insno" label="Installment Number" example=""/>


    <date-property required="yes" exist-on-table="yes" name="date" label="Paid Date" example=""/>

    <text-property name="description" label="Description" example=""/>


</regular-module>

=== ganganth/SSC_studentManagemnt_Syatem/XML/modules/discount.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE regular-module SYSTEM "../dtd/regular-module.dtd">
<regular-module name="discount" to-string-ts="discount.code + '-' + discount.nametitle.name + ' ' + discount.callingname" to-string-java="discount.getCode() + #quat;-#quat; + discount.getNametitle.getName() + #quat; #quat; + discount.getCallingname()">
    <code length="10" prefix="D" searchable="yes" exist-on-table="yes"/>


    <varchar-property basic="yes" exist-on-table="yes" searchable="yes" required="yes" width="8" name="name" label="Name" example=""/>

    <decimal-property name="fixedamount" label="Fixed Amount" example="" precision="10" scale="2" min="0" max="99999999"/>
    <decimal-property name="percentage" label="Percentage" example="" precision="5" scale="2" min="0" max="100"/>


    <reference-property basic="yes" searchable="yes" required="yes" name="discounttype" label="Discount Type" referenced-from="discounttype" service-method="getAll" to-string-java="discounttype.getName()" to-string-ts="discounttype.name"/>
    <reference-property basic="yes" searchable="yes" required="yes" insertable="no" default-value="1" name="discountstatus" label="Discount Status" referenced-from="discountstatus" service-method="getAll" to-string-java="discountstatus.getName()" to-string-ts="discountstatus.name"/>


    <text-property name="description" label="Description" example=""/>


</regular-module>

=== ganganth/SSC_studentManagemnt_Syatem/XML/modules/enrollment.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE regular-module SYSTEM "../dtd/regular-module.dtd">
<regular-module name="enrollment" to-string-ts="enrollment.code" to-string-java="enrollment.getCode()">
    <code length="10" prefix="EN" searchable="yes" exist-on-table="yes"/>

    <decimal-property name="discountamount" label="Discount Amount" example="" precision="10" scale="2" min="0" max="99999999"/>
    <decimal-property exist-on-table="yes" required="yes" name="fee" label="Total Fee" example="" precision="10" scale="2" min="0" max="99999999"/>
    <decimal-property insertable="no" updatable="no" name="balance" label="Balance" example="" precision="10" scale="2" min="0" max="99999999   "/>

    <reference-property basic="yes" required="yes" name="student" label="Student" referenced-from="student" service-method="getAllBasic" to-string-java="student.getCode() + #quat;-#quat; + student.getNametitle.getName() + #quat; #quat; + student.getCallingname()" to-string-ts="student.code + '-' + student.nametitle.name + ' ' + student.callingname"/>


    <reference-property required="yes" name="payscheme" label="Pay Scheme" referenced-from="payscheme" service-method="getAll" to-string-java="payscheme.getName()" to-string-ts="payscheme.name"/>

    <reference-property required="yes" name="gradeyear" label="Grade Year" referenced-from="gradeyear" service-method="getAllBasic" to-string-java="gradeyear.getCode() + #quat; #quat; + gradeyear.getYear()" to-string-ts="gradeyear.code + '-' + gradeyear.year"/>

    <reference-property required="yes" name="enrollmentstatus" label="Enrollment Status" referenced-from="enrollmentstatus" service-method="getAll" to-string-java="enrollmentstatus.getName()" to-string-ts="enrollmentstatus.name"/>

    <multiple-reference-property name="enrollmentdiscount" label="Enrollment Discount" to-string-java="discount.getName()" to-string-ts="discount.name" service-method="getAllBasic"
                                 referenced-from="discount"/>

    <text-property name="description" label="Description" example=""/>


</regular-module>

=== ganganth/SSC_studentManagemnt_Syatem/XML/modules/materialissue.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE regular-module SYSTEM "../dtd/regular-module.dtd">
<regular-module name="materialissue" to-string-ts="materialissue.code" to-string-java="materialissue.getCode()">

    <code length="10" prefix="MI" searchable="yes" exist-on-table="yes"/>

    <reference-property exist-on-table="yes" name="student" label="Student" to-string-java="student.getCallingname() + #quat;-#quat; + student.getCode()" to-string-ts="student.name + '-' + student.code" service-method="getAllBasic" referenced-from="student" basic="yes"/>

    <reference-property exist-on-table="yes" name="material" label="Material" to-string-java="material.getTitle()" to-string-ts="material.title" service-method="getAllBasic" referenced-from="material" basic="yes"/>
    <reference-property searchable="yes" exist-on-table="yes" required="yes" name="gradeyear" label="Grade Year" referenced-from="gradeyear" service-method="getAllBasic" to-string-java="gradeyear.getCode() + #quat; #quat; + gradeyear.getYear()" to-string-ts="gradeyear.code + '-' + gradeyear.year"/>

    <reference-property required="yes" exist-on-table="yes" searchable="yes" name="cls" label="Class" to-string-java="cls.getName()" to-string-ts="class.name" service-method="getAllBasic" referenced-from="cls"/>



    <date-property name="date" exist-on-table="yes" insertable="no" label="Date of Issued" example="02-03-2022"/>

    <text-property name="description" label="Description" example=""/>
</regular-module>

=== ganganth/SSC_studentManagemnt_Syatem/XML/modules/cls.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE regular-module SYSTEM "../dtd/regular-module.dtd">
<regular-module name="cls" to-string-ts="cls.code + '-' + cls.name" to-string-java="cls.getCode() + #quat; #quat; + cls.getName()">
    <code length="10" prefix="C" searchable="yes" exist-on-table="yes"/>

    <varchar-property name="name" label="Subject Name" example="" required="yes" exist-on-table="yes" searchable="yes"/>

    <char-property name="year" label="Year" example="" size="4" exist-on-table="yes" required="yes"/>

    <reference-property required="yes" name="gradeyear" label="Grade Year" referenced-from="gradeyear" service-method="getAllBasic" to-string-java="gradeyear.getCode() + #quat; #quat; + gradeyear.getYear()" to-string-ts="gradeyear.code + '-' + gradeyear.year"/>

    <reference-property searchable="yes" required="yes" name="medium" label="Medium" referenced-from="medium" service-method="getAll" to-string-java="medium.getName()" to-string-ts="medium.name"/>

    <reference-property exist-on-table="yes" searchable="yes" required="yes" name="teacher" label="Homeroom Teacher" to-string-java="teacher.getCode() + #quat;-#quat; + teacher.getNametitle().getName() + #quat; #quat; + teacher.getCallingname()" to-string-ts="teacher.code + '-' + teacher.nametitle.name + ' ' + teacher.callingname" service-method="getAllBasic"
                        referenced-from="employee"/>

    <reference-property exist-on-table="yes" searchable="yes" required="yes" name="assistantteacher" label="Assistant Teacher" to-string-java="assistantteacher.getCode() + #quat;-#quat; + assistantteacher.getNametitle().getName() + #quat; #quat; + assistantteacher.getCallingname()" to-string-ts="assistantteacher.code + '-' + assistantteacher.nametitle.name + ' ' + assistantteacher.callingname" service-method="getAllBasic"
                        referenced-from="employee"/>

    <reference-property exist-on-table="yes" searchable="yes" name="monitor" label="Class Monitor" to-string-java="monitor.getCode() + #quat;-#quat; + monitor.getNametitle().getName() + #quat; #quat; + monitor.getCallingname()" to-string-ts="monitor.code + '-' + monitor.nametitle.name + ' ' + monitor.callingname" service-method="getAllBasic"
                        referenced-from="student"/>

    <reference-property exist-on-table="yes" searchable="yes" name="vicemonitor" label="Class Vice Monitor" to-string-java="vicemonitor.getCode() + #quat;-#quat; + vicemonitor.getNametitle().getName() + #quat; #quat; + vicemonitor.getCallingname()" to-string-ts="vicemonitor.code + '-' + vicemonitor.nametitle.name + ' ' + vicemonitor.callingname" service-method="getAllBasic"
                        referenced-from="student"/>

    <multiple-reference-property name="clsstudent" label="Class Students" to-string-java="clsstudent.getCode() + #quat;-#quat; + clsstudent.getNametitle().getName() + #quat; #quat; + clsstudent.getCallingname()" to-string-ts="clsstudent.code + '-' + clsstudent.nametitle.name + ' ' + clsstudent.callingname" service-method="getAllBasic"
                                 referenced-from="student"/>
    
    <sub-module name="clssubject" label="Class Subject" to-string-ts="clssubject.id" to-string-java="clssubject.getId()">
        <reference-property required="yes" name="subject" label="Subject" referenced-from="subject" service-method="getAllBasic" to-string-java="subject.getCode() + #quat; #quat; + subject.getName()" to-string-ts="subject.code + '-' + subject.name"/>
        <reference-property exist-on-table="yes" searchable="yes" required="yes" name="teacher" label="Subject Teacher" to-string-java="teacher.getCode() + #quat;-#quat; + teacher.getNametitle().getName() + #quat; #quat; + teacher.getCallingname()" to-string-ts="teacher.code + '-' + teacher.nametitle.name + ' ' + teacher.callingname" service-method="getAllBasic"
                            referenced-from="employee"/>
    </sub-module>

    <reference-property required="yes" name="clsstatus" label="Class Status" referenced-from="clsstatus" service-method="getAll" to-string-java="clsstatus.getName()" to-string-ts="clsstatus.name"/>

    <text-property name="description" label="Description" example=""/>

</regular-module>

=== ganganth/SSC_studentManagemnt_Syatem/XML/modules/employee.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE regular-module SYSTEM "../dtd/regular-module.dtd">
<regular-module name="employee" to-string-ts="employee.code + '-' + employee.nametitle.name + ' ' + employee.callingname" to-string-java="employee.getCode() + #quat;-#quat; + employee.getNametitle.getName() + #quat; #quat; + employee.getCallingname()">
    <code length="8" prefix="EM" searchable="yes" exist-on-table="yes"/>
    <group>
        <reference-property basic="yes" required="yes" width="4" name="nametitle" label="Title" referenced-from="nametitle" service-method="getAll" to-string-java="nametitle.getName()" to-string-ts="nametitle.name"/>
        <varchar-property basic="yes" exist-on-table="yes" searchable="yes" required="yes" width="8" name="callingname" label="Calling Name" example="Sandun"/>
    </group>
    <group>
        <reference-property width="4" name="civilstatus" label="Civilstatus" referenced-from="civilstatus" service-method="getAll" to-string-ts="civilstatus.name" to-string-java="civilstatus.getName()"/>
        <varchar-property width="8" required="yes" name="fullname" label="Full Name" example="Kamal Perera"/>
    </group>
    <file-property basic="yes" name="photo" label="Photo" accept="image/*" exist-on-table="yes"/>
    <group>
        <date-property required="yes" width="4" name="dobirth" label="Date Of Birth" example="1994-12-31"/>
        <reference-property required="yes" width="4" name="gender" label="Gender" referenced-from="gender" service-method="getAll" to-string-java="gender.getName()" to-string-ts="gender.name"/>
        <varchar-property unique="yes" required="yes" exist-on-table="yes" searchable="yes" width="4" name="nic" label="NIC Number" example="940081009V" min-length="10" max-length="12" pattern="^(([0-9]{12})|([0-9]{9}[vVxX]))$"/>
    </group>
    <group>
        <char-property unique="yes" name="mobile" label="Mobile Number" example="0789456123" size="10" required="yes" width="4" pattern="^([0][0-9]{9})$"/>
        <char-property name="land" label="Land Number" example="0789455123" size="10" width="4" pattern="^([0][0-9]{9})$"/>
        <varchar-property unique="yes" width="4" name="email" label="Email Address" example="user@gmail.com" min-length="5" pattern="^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$"/>
    </group>
    <text-property name="address" label="Address" example="123, Colombo Road, Gampaha" min-length="4" required="yes"/>
    <reference-property required="yes" name="designation" label="Designation" referenced-from="designation" exist-on-table="yes" service-method="getAll" to-string-ts="designation.name" to-string-java="designation.getName()"/>
    <reference-property required="yes" default-value="1" insertable="no" searchable="yes" exist-on-table="yes" name="employeestatus" label="Status" referenced-from="employeestatus" service-method="getAll" to-string-java="employeestatus.getName()" to-string-ts="employeestatus.name"/>
    <text-property name="description" label="Description" example=""/>

</regular-module>
