=== ganganth/SSC_studentManagemnt_Syatem/XML/dtd/seed.dtd
<!ELEMENT seed (properties, values)>
<!ELEMENT properties (char-property|varchar-property|text-property|int-property|decimal-property|boolean-property|date-property|datetime-property|time-property)+>
<!ELEMENT values (value+)>
<!ELEMENT value (data+)>
<!ELEMENT data (#PCDATA)>

<!ELEMENT char-property EMPTY>
<!ELEMENT varchar-property EMPTY>
<!ELEMENT text-property EMPTY>
<!ELEMENT int-property EMPTY>
<!ELEMENT decimal-property EMPTY>
<!ELEMENT boolean-property EMPTY>
<!ELEMENT date-property EMPTY>
<!ELEMENT datetime-property EMPTY>
<!ELEMENT time-property EMPTY>

<!ENTITY % props 'name CDATA #REQUIRED size CDATA #REQUIRED'>
<!ATTLIST char-property %props;>
<!ATTLIST varchar-property %props;>
<!ATTLIST text-property name CDATA #REQUIRED>
<!ATTLIST int-property name CDATA #REQUIRED size (1|2|3|4|5|6|7|8|9|10|11) #REQUIRED>
<!ATTLIST boolean-property name CDATA #REQUIRED>
<!ATTLIST date-property name CDATA #REQUIRED>
<!ATTLIST time-property name CDATA #REQUIRED>
<!ATTLIST datetime-property name CDATA #REQUIRED>
<!ATTLIST decimal-property name CDATA #REQUIRED precision  CDATA #REQUIRED scale CDATA #REQUIRED>

<!ATTLIST seed name CDATA #REQUIRED>
<!ATTLIST seed to-string CDATA #REQUIRED>

=== ganganth/SSC_studentManagemnt_Syatem/XML/seeds/day.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE seed SYSTEM "../dtd/seed.dtd">
<seed name="day" to-string="{name}">
    <properties>
        <varchar-property name="name" size="20"/>
    </properties>
    <values>
        <value><data>Monday</data></value>
        <value><data>Tuesday</data></value>
        <value><data>Wednesday</data></value>
        <value><data>Thursday</data></value>
        <value><data>Friday</data></value>
        <value><data>Saturday</data></value>
        <value><data>Sunday</data></value>
    </values>
</seed>

=== ganganth/SSC_studentManagemnt_Syatem/XML/seeds/house.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE seed SYSTEM "../dtd/seed.dtd">
<seed name="house" to-string="{name}">
    <properties>
        <varchar-property name="name" size="20"/>
    </properties>
    <values>
        <value><data>A</data></value>
        <value><data>B</data></value>
        <value><data>C</data></value>
    </values>
</seed>

=== ganganth/SSC_studentManagemnt_Syatem/XML/seeds/medium.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE seed SYSTEM "../dtd/seed.dtd">
<seed name="medium" to-string="{name}">
    <properties>
        <varchar-property name="name" size="20"/>
    </properties>
    <values>
        <value><data>English</data></value>
        <value><data>Sinhala</data></value>
    </values>
</seed>

=== ganganth/SSC_studentManagemnt_Syatem/XML/seeds/gradeyearstatus.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE seed SYSTEM "../dtd/seed.dtd">
<seed name="gradeyearstatus" to-string="{name}">
    <properties>
        <varchar-property name="name" size="20"/>
    </properties>
    <values>
        <value><data>Active</data></value>
        <value><data>Finished</data></value>
        <value><data>Cancelled</data></value>
    </values>
</seed>

=== ganganth/SSC_studentManagemnt_Syatem/XML/seeds/enrollmentstatus.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE seed SYSTEM "../dtd/seed.dtd">
<seed name="enrollmentstatus" to-string="{name}">
    <properties>
        <varchar-property name="name" size="20"/>
    </properties>
    <values>
        <value>
            <data>A</data>
        </value>
        <value>
            <data>B</data>
        </value>
    </values>
</seed>

=== ganganth/SSC_studentManagemnt_Syatem/XML/seeds/guardianrelationship.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE seed SYSTEM "../dtd/seed.dtd">
<seed name="guardianrelationship" to-string="{name}">
    <properties>
        <varchar-property name="name" size="20"/>
    </properties>
    <values>
        <value><data>Father</data></value>
        <value><data>Mother</data></value>
        <value><data>Legal Guardian</data></value>
    </values>
</seed>

=== ganganth/SSC_studentManagemnt_Syatem/XML/seeds/lessonstatus.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE seed SYSTEM "../dtd/seed.dtd">
<seed name="lessonstatus" to-string="{name}">
    <properties>
        <varchar-property name="name" size="20"/>
    </properties>
    <values>
        <value><data>Available</data></value>
        <value><data>Discontinued</data></value>
    </values>
</seed>

=== ganganth/SSC_studentManagemnt_Syatem/XML/seeds/grade.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE seed SYSTEM "../dtd/seed.dtd">
<seed name="grade" to-string="{name}">
    <properties>
        <varchar-property name="name" size="20"/>
    </properties>
    <values>
        <value><data>Grade 1</data></value>
        <value><data>Grade 2</data></value>
        <value><data>Grade 3</data></value>
        <value><data>Grade 4</data></value>
        <value><data>Grade 5</data></value>
    </values>
</seed>
