=== ganganth/SSC_studentManagemnt_Syatem/XML/dtd/seed.dtd
<!ELEMENT seed (properties, values)>
<!ELEMENT properties (char-property|varchar-property|text-property|int-property|decimal-property|boolean-property|date-property|datetime-property|time-property)+>
<!ELEMENT values (value+)>
<!ELEMENT value (data+)>
<!ELEMENT data (#PCDATA)>

<!ELEMENT char-property EMPTY>
<!ELEMENT varchar-property EMPTY>
<!ELEMENT text-property EMPTY>
<!ELEMENT int-property EMPTY>
<!ELEMENT decimal-property EMPTY>
<!ELEMENT boolean-property EMPTY>
<!ELEMENT date-property EMPTY>
<!ELEMENT datetime-property EMPTY>
<!ELEMENT time-property EMPTY>

<!ENTITY % props 'name CDATA #REQUIRED size CDATA #REQUIRED'>
<!ATTLIST char-property %props;>
<!ATTLIST varchar-property %props;>
<!ATTLIST text-property name CDATA #REQUIRED>
<!ATTLIST int-property name CDATA #REQUIRED size (1|2|3|4|5|6|7|8|9|10|11) #REQUIRED>
<!ATTLIST boolean-property name CDATA #REQUIRED>
<!ATTLIST date-property name CDATA #REQUIRED>
<!ATTLIST time-property name CDATA #REQUIRED>
<!ATTLIST datetime-property name CDATA #REQUIRED>
<!ATTLIST decimal-property name CDATA #REQUIRED precision  CDATA #REQUIRED scale CDATA #REQUIRED>

<!ATTLIST seed name CDATA #REQUIRED>
<!ATTLIST seed to-string CDATA #REQUIRED>

=== ganganth/SSC_studentManagemnt_Syatem/XML/seeds/clssessionstatus.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE seed SYSTEM "../dtd/seed.dtd">
<seed name="clssessionstatus" to-string="{name}">
    <properties>
        <varchar-property name="name" size="20"/>
    </properties>
    <values>
        <value><data>Pending</data></value>
        <value><data>Done</data></value>
    </values>
</seed>

=== ganganth/SSC_studentManagemnt_Syatem/XML/seeds/gender.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE seed SYSTEM "../dtd/seed.dtd">
<seed name="gender" to-string="{name}">
    <properties>
        <varchar-property name="name" size="10"/>
    </properties>
    <values>
        <value>
            <data>Male</data>
        </value>
        <value>
            <data>Female</data>
        </value>
    </values>
</seed>

=== ganganth/SSC_studentManagemnt_Syatem/XML/seeds/sheduledatestatus.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE seed SYSTEM "../dtd/seed.dtd">
<seed name="sheduledatestatus" to-string="{name}">
    <properties>
        <varchar-property name="name" size="20"/>
    </properties>
    <values>
        <value><data>Scheduled</data></value>
        <value><data>Cancelled</data></value>
    </values>
</seed>

=== ganganth/SSC_studentManagemnt_Syatem/XML/seeds/payscheme.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE seed SYSTEM "../dtd/seed.dtd">
<seed name="payscheme" to-string="{name}">
    <properties>
        <varchar-property name="name" size="20"/>
    </properties>
    <values>
        <value><data>Full</data></value>
        <value><data>Installment</data></value>
    </values>
</seed>

=== ganganth/SSC_studentManagemnt_Syatem/XML/seeds/designation.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE seed SYSTEM "../dtd/seed.dtd">
<seed name="designation" to-string="{name}">
    <properties>
        <varchar-property name="name" size="25"/>
    </properties>
    <values>
        <value><data>Teacher</data></value>
        <value><data>Principal</data></value>
        <value><data>Non-Academic</data></value>
    </values>
</seed>

=== ganganth/SSC_studentManagemnt_Syatem/XML/seeds/civilstatus.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE seed SYSTEM "../dtd/seed.dtd">
<seed name="civilstatus" to-string="{name}">
    <properties>
        <varchar-property name="name" size="12"/>
    </properties>
    <values>
        <value><data>Single</data></value>
        <value><data>Married</data></value>
        <value><data>Other</data></value>
    </values>
</seed>

=== ganganth/SSC_studentManagemnt_Syatem/XML/seeds/timetablestatus.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE seed SYSTEM "../dtd/seed.dtd">
<seed name="timetablestatus" to-string="{name}">
    <properties>
        <varchar-property name="name" size="20"/>
    </properties>
    <values>
        <value><data>Ongoing</data></value>
        <value><data>Finished</data></value>
    </values>
</seed>

=== ganganth/SSC_studentManagemnt_Syatem/XML/seeds/ethnicity.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE seed SYSTEM "../dtd/seed.dtd">
<seed name="ethnicity" to-string="{name}">
    <properties>
        <varchar-property name="name" size="20"/>
    </properties>
    <values>
        <value><data>Sinhalese</data></value>
        <value><data>Tamil</data></value>
        <value><data>Muslim</data></value>
    </values>
</seed>
