=== ganganth/SSC_studentManagemnt_Syatem/XML/dtd/seed.dtd
<!ELEMENT seed (properties, values)>
<!ELEMENT properties (char-property|varchar-property|text-property|int-property|decimal-property|boolean-property|date-property|datetime-property|time-property)+>
<!ELEMENT values (value+)>
<!ELEMENT value (data+)>
<!ELEMENT data (#PCDATA)>

<!ELEMENT char-property EMPTY>
<!ELEMENT varchar-property EMPTY>
<!ELEMENT text-property EMPTY>
<!ELEMENT int-property EMPTY>
<!ELEMENT decimal-property EMPTY>
<!ELEMENT boolean-property EMPTY>
<!ELEMENT date-property EMPTY>
<!ELEMENT datetime-property EMPTY>
<!ELEMENT time-property EMPTY>

<!ENTITY % props 'name CDATA #REQUIRED size CDATA #REQUIRED'>
<!ATTLIST char-property %props;>
<!ATTLIST varchar-property %props;>
<!ATTLIST text-property name CDATA #REQUIRED>
<!ATTLIST int-property name CDATA #REQUIRED size (1|2|3|4|5|6|7|8|9|10|11) #REQUIRED>
<!ATTLIST boolean-property name CDATA #REQUIRED>
<!ATTLIST date-property name CDATA #REQUIRED>
<!ATTLIST time-property name CDATA #REQUIRED>
<!ATTLIST datetime-property name CDATA #REQUIRED>
<!ATTLIST decimal-property name CDATA #REQUIRED precision  CDATA #REQUIRED scale CDATA #REQUIRED>

<!ATTLIST seed name CDATA #REQUIRED>
<!ATTLIST seed to-string CDATA #REQUIRED>

=== ganganth/SSC_studentManagemnt_Syatem/XML/seeds/nametitle.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE seed SYSTEM "../dtd/seed.dtd">
<seed name="nametitle" to-string="{name}">
    <properties>
        <varchar-property name="name" size="10"/>
    </properties>
    <values>
        <value><data>Mr.</data></value>
        <value><data>Miss</data></value>
        <value><data>Mrs.</data></value>
        <value><data>Rev.</data></value>
    </values>
</seed>

=== ganganth/SSC_studentManagemnt_Syatem/XML/seeds/discountstatus.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE seed SYSTEM "../dtd/seed.dtd">
<seed name="discountstatus" to-string="{name}">
    <properties>
        <varchar-property name="name" size="20"/>
    </properties>
    <values>
        <value><data>Active</data></value>
        <value><data>Deactivated</data></value>
    </values>
</seed>

=== ganganth/SSC_studentManagemnt_Syatem/XML/seeds/religion.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE seed SYSTEM "../dtd/seed.dtd">
<seed name="religion" to-string="{name}">
    <properties>
        <varchar-property name="name" size="20"/>
    </properties>
    <values>
        <value><data>Buddhist</data></value>
        <value><data>Catholic</data></value>
        <value><data>Muslim</data></value>
    </values>
</seed>

=== ganganth/SSC_studentManagemnt_Syatem/XML/seeds/bloodtype.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE seed SYSTEM "../dtd/seed.dtd">
<seed name="bloodtype" to-string="{name}">
    <properties>
        <varchar-property name="name" size="12"/>
    </properties>
    <values>
        <value><data>A+</data></value>
        <value><data>A-</data></value>
        <value><data>B+</data></value>
        <value><data>B-</data></value>
        <value><data>C+</data></value>
        <value><data>C-</data></value>
        <value><data>O+</data></value>
        <value><data>O-</data></value>
    </values>
</seed>

=== ganganth/SSC_studentManagemnt_Syatem/XML/seeds/discounttype.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE seed SYSTEM "../dtd/seed.dtd">
<seed name="discounttype" to-string="{name}">
    <properties>
        <varchar-property name="name" size="20"/>
    </properties>
    <values>
        <value><data>Alumni</data></value>
        <value><data>Promotion</data></value>
        <value><data>Other</data></value>
    </values>
</seed>
